"""App database (app.db) for views, strategies, paper portfolios."""

from src.db.app_db import (
    get_app_db_path,
    init_app_db,
    # Dashboard views
    list_dashboard_views,
    get_dashboard_view,
    create_dashboard_view,
    update_dashboard_view,
    delete_dashboard_view,
    # Strategies
    list_strategies,
    get_strategy,
    get_global_default_strategy,
    create_strategy,
    update_strategy,
    set_global_default_strategy,
    delete_strategy,
    # Symbol universe
    list_universe_symbols,
    add_universe_symbol,
    remove_universe_symbol,
    set_universe_symbols,
    # Paper portfolios
    list_paper_portfolios,
    get_paper_portfolio,
    create_paper_portfolio,
    update_paper_portfolio,
    delete_paper_portfolio,
    list_paper_positions,
    set_paper_positions,
    add_paper_position,
    remove_paper_position,
    # Paper equity snapshots
    append_paper_snapshot,
    get_paper_snapshots,
)

__all__ = [
    "get_app_db_path",
    "init_app_db",
    "list_dashboard_views",
    "get_dashboard_view",
    "create_dashboard_view",
    "update_dashboard_view",
    "delete_dashboard_view",
    "list_strategies",
    "get_strategy",
    "get_global_default_strategy",
    "create_strategy",
    "update_strategy",
    "set_global_default_strategy",
    "delete_strategy",
    "list_universe_symbols",
    "add_universe_symbol",
    "remove_universe_symbol",
    "set_universe_symbols",
    "list_paper_portfolios",
    "get_paper_portfolio",
    "create_paper_portfolio",
    "update_paper_portfolio",
    "delete_paper_portfolio",
    "list_paper_positions",
    "set_paper_positions",
    "add_paper_position",
    "remove_paper_position",
    "append_paper_snapshot",
    "get_paper_snapshots",
]
